[theme]
# Primary colors
primaryColor="#ffffff"



# Background color for the sidebar and most interactive widgets
secondaryBackgroundColor="#1e3f5c"

# Color used for almost all text
textColor="#000000"

# Color used for all text in the header area, including the streamlit logo text
headerTextColor="#000000"
