[theme]
# Primary colors
primaryColor="#ffffff"

# Background colors for the main content area
backgroundColor="#262730"

# Background color for the sidebar and most interactive widgets
secondaryBackgroundColor="#1e3f5c"

# Color used for almost all text
textColor="#ffffff"

# Color used for all text in the header area, including the streamlit logo text
headerTextColor="#ffffff"
